/// <reference path="../node_modules/@citizenfx/client/natives_universal.d.ts" />

const STREET_HASHES = {
  [String(GetHashKey("ABBATAVE"))]: "Abattoir Ave",
  [String(GetHashKey("ABEMIL"))]: "Abe Milton Pkwy",
  [String(GetHashKey("ACEJONES"))]: "Ace Jones Dr",
  [String(GetHashKey("ADAMSA"))]: "Adam's Apple Blvd",
  [String(GetHashKey("AGUJA"))]: "Aguja St",
  [String(GetHashKey("ALGONQUIN"))]: "Algonquin Blvd",
  [String(GetHashKey("ALHAMBRA"))]: "Alhambra Dr",
  [String(GetHashKey("ALTAPL"))]: "Alta Pl",
  [String(GetHashKey("ALT_ST"))]: "Alta St",
  [String(GetHashKey("AMARIL"))]: "Amarillo Vista",
  [String(GetHashKey("AMARILLOW"))]: "Amarillo Way",
  [String(GetHashKey("AMERICANO"))]: "Americano Way",
  [String(GetHashKey("ANTWERP"))]: "Jamestown St",
  [String(GetHashKey("ARMADILLO"))]: "Armadillo Ave",
  [String(GetHashKey("AUTOPI"))]: "Autopia Pkwy",
  [String(GetHashKey("BACKLOTF"))]: "Olympic Fwy",
  [String(GetHashKey("BANHAMC"))]: "Banham Canyon Dr",
  [String(GetHashKey("BARBAREN"))]: "Barbareno Rd",
  [String(GetHashKey("BAYCAVE"))]: "Bay City Ave",
  [String(GetHashKey("BAYCI"))]: "Bay City Incline",
  [String(GetHashKey("BAYTREECAN"))]: "Baytree Canyon Rd",
  [String(GetHashKey("BOULDELP"))]: "Boulevard Del Perro",
  [String(GetHashKey("BRIDGES"))]: "Bridge St",
  [String(GetHashKey("BUCCA"))]: "Buccaneer Way",
  [String(GetHashKey("BUENVIN"))]: "Buen Vino Rd",
  [String(GetHashKey("CAEP"))]: "Caesars Place",
  [String(GetHashKey("CALAF"))]: "Calafia Rd",
  [String(GetHashKey("CALFN"))]: "North Calafia Way",
  [String(GetHashKey("CAPITALB"))]: "Capital Blvd",
  [String(GetHashKey("CARCER"))]: "Carcer Way",
  [String(GetHashKey("CARSONA"))]: "Carson Ave",
  [String(GetHashKey("CASCABEL"))]: "Cascabel Ave",
  [String(GetHashKey("CASSITRA"))]: "Cassidy Trail",
  [String(GetHashKey("CATCL"))]: "Cat-Claw Ave",
  [String(GetHashKey("CATVIEW"))]: "Catfish View",
  [String(GetHashKey("CAVAL"))]: "Cavalry Blvd",
  [String(GetHashKey("CHAR_ST"))]: "San Andreas Ave",
  [String(GetHashKey("CHIPASS"))]: "Chianski Passage",
  [String(GetHashKey("CHOLLA"))]: "Cholla Springs Ave",
  [String(GetHashKey("CHOLLAR"))]: "Cholla Rd",
  [String(GetHashKey("CHUM"))]: "Chum St",
  [String(GetHashKey("CHUP"))]: "Chupacabra St",
  [String(GetHashKey("CLINTONA"))]: "Clinton Ave",
  [String(GetHashKey("COCKING"))]: "Cockingend Dr",
  [String(GetHashKey("CONQUIS"))]: "Conquistador St",
  [String(GetHashKey("CORTES"))]: "Cortes St",
  [String(GetHashKey("COUGARA"))]: "Cougar Ave",
  [String(GetHashKey("COXW"))]: "Cox Way",
  [String(GetHashKey("CRUSADE"))]: "Crusade Rd",
  [String(GetHashKey("DAVISA"))]: "Davis Ave",
  [String(GetHashKey("DECKERS"))]: "Decker St",
  [String(GetHashKey("DELPFWY"))]: "Del Perro Fwy",
  [String(GetHashKey("DENKER"))]: "Brouge Ave",
  [String(GetHashKey("DIDIO"))]: "Didion Dr",
  [String(GetHashKey("DORSE"))]: "Dorset Dr",
  [String(GetHashKey("DORSEP"))]: "Dorset Pl",
  [String(GetHashKey("DRYDOCK"))]: "Dry Dock St",
  [String(GetHashKey("DULUOZ"))]: "Duluoz Ave",
  [String(GetHashKey("DUND"))]: "Dunstable Dr",
  [String(GetHashKey("DUNL"))]: "Dunstable Ln",
  [String(GetHashKey("DUTCHTO"))]: "Dutch London St",
  [String(GetHashKey("EASTBOR"))]: "Eastbourne Way",
  [String(GetHashKey("ECLIPBLV"))]: "Eclipse Blvd",
  [String(GetHashKey("EDWOOD"))]: "Edwood Way",
  [String(GetHashKey("EGAL"))]: "East Galileo Ave",
  [String(GetHashKey("ELBURROB"))]: "El Burro Blvd",
  [String(GetHashKey("ELGIN"))]: "Elgin Ave",
  [String(GetHashKey("ELRANC"))]: "El Rancho Blvd",
  [String(GetHashKey("ELYFIFWY"))]: "Elysian Fields Fwy",
  [String(GetHashKey("EMIRROR"))]: "East Mirror Dr",
  [String(GetHashKey("EQUALITYW"))]: "Equality Way",
  [String(GetHashKey("EXCEPTI"))]: "Exceptionalists Way",
  [String(GetHashKey("FANTASPL"))]: "Fantastic Pl",
  [String(GetHashKey("FENWELL"))]: "Fenwell Pl",
  [String(GetHashKey("FLO_ST"))]: "Power St",
  [String(GetHashKey("FORTZAN"))]: "Fort Zancudo Approach Rd",
  [String(GetHashKey("FORUMD"))]: "Forum Dr",
  [String(GetHashKey("FUDGEL"))]: "Fudge Ln",
  [String(GetHashKey("GALIR"))]: "Galileo Rd",
  [String(GetHashKey("GALLI"))]: "Galileo Park",
  [String(GetHashKey("GENTRYL"))]: "Gentry Lane",
  [String(GetHashKey("GINGERS"))]: "Ginger St",
  [String(GetHashKey("GLORYW"))]: "Glory Way",
  [String(GetHashKey("GOHIGH"))]: "Great Ocean Hwy",
  [String(GetHashKey("GOMA"))]: "Goma St",
  [String(GetHashKey("GRAPSEEDA"))]: "Grapeseed Ave",
  [String(GetHashKey("GRAPSEEDM"))]: "Grapeseed Main St",
  [String(GetHashKey("GREENWICHP"))]: "Greenwich Pl",
  [String(GetHashKey("GREENWP"))]: "Greenwich Pkwy",
  [String(GetHashKey("GREEWICHW"))]: "Greenwich Way",
  [String(GetHashKey("GROVE"))]: "Grove St",
  [String(GetHashKey("HANGER"))]: "Hanger Way",
  [String(GetHashKey("HANGMAN"))]: "Hangman Ave",
  [String(GetHashKey("HANWELL"))]: "Hillcrest Ave",
  [String(GetHashKey("HARBORFWY"))]: "Olympic Fwy",
  [String(GetHashKey("HARDY"))]: "Hardy Way",
  [String(GetHashKey("HAWIK"))]: "Hawick Ave",
  [String(GetHashKey("HERITAGE"))]: "Heritage Way",
  [String(GetHashKey("HILLCA"))]: "Hillcrest Ridge Access Rd",
  [String(GetHashKey("HOOPR"))]: "Covenant Ave",
  [String(GetHashKey("IMAGIN"))]: "Imagination Ct",
  [String(GetHashKey("INESE"))]: "Ineseno Road",
  [String(GetHashKey("INNNOC"))]: "Innocence Blvd",
  [String(GetHashKey("INTEG"))]: "Integrity Way",
  [String(GetHashKey("INVEN"))]: "Invention Ct",
  [String(GetHashKey("JOAD"))]: "Joad Ln",
  [String(GetHashKey("JOSHE"))]: "East Joshua Road",
  [String(GetHashKey("JOSHR"))]: "Joshua Rd",
  [String(GetHashKey("KIMBLE"))]: "Kimble Hill Dr",
  [String(GetHashKey("KORTZ"))]: "Kortz Dr",
  [String(GetHashKey("LABORP"))]: "Labor Pl",
  [String(GetHashKey("LAGUNP"))]: "Laguna Pl",
  [String(GetHashKey("LAKEVINDR"))]: "Lake Vinewood Dr",
  [String(GetHashKey("LAKEVINES"))]: "Lake Vinewood Est",
  [String(GetHashKey("LASLAGB"))]: "Las Lagunas Blvd",
  [String(GetHashKey("LBHORN"))]: "Little Bighorn Ave",
  [String(GetHashKey("LESBOSL"))]: "Lesbos Ln",
  [String(GetHashKey("LIBERTYST"))]: "Liberty St",
  [String(GetHashKey("LINDSAYC"))]: "Lindsay Circus",
  [String(GetHashKey("LOLITA"))]: "Lolita Ave",
  [String(GetHashKey("LOSPFY"))]: "La Puerta Fwy",
  [String(GetHashKey("LOSSF"))]: "Los Santos Freeway",
  [String(GetHashKey("LOWPOW"))]: "Low Power St",
  [String(GetHashKey("MACDST"))]: "Macdonald St",
  [String(GetHashKey("MAGELAN"))]: "Magellan Ave",
  [String(GetHashKey("MARATHON"))]: "Marathon Ave",
  [String(GetHashKey("MARINAD"))]: "Marina Dr",
  [String(GetHashKey("MARL"))]: "Marlowe Dr",
  [String(GetHashKey("MELAN"))]: "Melanoma St",
  [String(GetHashKey("MERINGUE"))]: "Meringue Ln",
  [String(GetHashKey("METEOR"))]: "Meteor St",
  [String(GetHashKey("MILTON"))]: "Milton Rd",
  [String(GetHashKey("MIRIAMT"))]: "Miriam Turner Overpass",
  [String(GetHashKey("MIRRORP"))]: "Mirror Pl",
  [String(GetHashKey("MIRRPB"))]: "Mirror Park Blvd",
  [String(GetHashKey("MORNWOOD"))]: "Morningwood Blvd",
  [String(GetHashKey("MOUNTAV"))]: "Mountain View Dr",
  [String(GetHashKey("MTHAAN"))]: "Mt Haan Rd",
  [String(GetHashKey("MTHAANDR"))]: "Mt Haan Dr",
  [String(GetHashKey("MTVINEWOD"))]: "Mt Vinewood Dr",
  [String(GetHashKey("MUTIN"))]: "Mutiny Rd",
  [String(GetHashKey("MVSTARS"))]: "Movie Star Way",
  [String(GetHashKey("NARCH"))]: "North Archer Ave",
  [String(GetHashKey("NCONKER"))]: "North Conker Ave",
  [String(GetHashKey("NEWEMPIRE"))]: "New Empire Way",
  [String(GetHashKey("NIKOLAA"))]: "Nikola Ave",
  [String(GetHashKey("NIKOLAP"))]: "Nikola Pl",
  [String(GetHashKey("NILAND"))]: "Niland Ave",
  [String(GetHashKey("NMADJOE"))]: "Mad Wayne Thunder Dr",
  [String(GetHashKey("NORMAND"))]: "Normandy Dr",
  [String(GetHashKey("NOWHE"))]: "Nowhere Rd",
  [String(GetHashKey("NPOP"))]: "Popular St",
  [String(GetHashKey("NROCK"))]: "North Rockford Dr",
  [String(GetHashKey("NSHELDON"))]: "North Sheldon Ave",
  [String(GetHashKey("N_BOULDP"))]: "Boulevard Del Perro",
  [String(GetHashKey("OCCUPA"))]: "Occupation Ave",
  [String(GetHashKey("ONEIL"))]: "O'Neil Way",
  [String(GetHashKey("ORCHARDV"))]: "Orchardville Ave",
  [String(GetHashKey("PALETOB"))]: "Paleto Blvd",
  [String(GetHashKey("PALOMFREE"))]: "Palomino Fwy",
  [String(GetHashKey("PALOMINO"))]: "Palomino Ave",
  [String(GetHashKey("PANORAMA"))]: "Panorama Dr",
  [String(GetHashKey("PEACEF"))]: "Peaceful St",
  [String(GetHashKey("PERTHA"))]: "Perth St",
  [String(GetHashKey("PLAICE"))]: "Plaice Pl",
  [String(GetHashKey("PLAYAVI"))]: "Playa Vista",
  [String(GetHashKey("PORTOLA"))]: "Portola Dr",
  [String(GetHashKey("PPWAY"))]: "Picture Perfect Drive",
  [String(GetHashKey("PROCO"))]: "Procopio Dr",
  [String(GetHashKey("PROCOP"))]: "Procopio Promenade",
  [String(GetHashKey("PRODUST"))]: "Supply St",
  [String(GetHashKey("PROSPERI"))]: "Prosperity St",
  [String(GetHashKey("PYRITE"))]: "Pyrite Ave",
  [String(GetHashKey("REDDES"))]: "Red Desert Ave",
  [String(GetHashKey("RICHMST"))]: "Richman St",
  [String(GetHashKey("ROCKD"))]: "Rockford Dr",
  [String(GetHashKey("ROYLO"))]: "Roy Lowenstein Blvd",
  [String(GetHashKey("RT68"))]: "Route 68",
  [String(GetHashKey("RT68APP"))]: "Route 68 Approach",
  [String(GetHashKey("RUBST"))]: "Rub St",
  [String(GetHashKey("RUNWAY1"))]: "Runway1",
  [String(GetHashKey("SAMAUS"))]: "Sam Austin Dr",
  [String(GetHashKey("SANDYC"))]: "Sandcastle Way",
  [String(GetHashKey("SEAV"))]: "Seaview Rd",
  [String(GetHashKey("SENORA"))]: "Senora Fwy",
  [String(GetHashKey("SENORARD"))]: "Senora Rd",
  [String(GetHashKey("SENORWAY"))]: "Senora Way",
  [String(GetHashKey("SHANK"))]: "Shank St",
  [String(GetHashKey("SIGNALST"))]: "Signal St",
  [String(GetHashKey("SINPA"))]: "Sinners Passage",
  [String(GetHashKey("SINST"))]: "Sinner St",
  [String(GetHashKey("SMADJOE"))]: "Mad Wayne Thunder Dr",
  [String(GetHashKey("SMOKET"))]: "Smoke Tree Rd",
  [String(GetHashKey("SMOMIL"))]: "South Mo Milton Dr",
  [String(GetHashKey("SNORMAV"))]: "Calais Ave",
  [String(GetHashKey("SPANAV"))]: "Spanish Ave",
  [String(GetHashKey("SROCK"))]: "South Rockford Dr",
  [String(GetHashKey("SSHAM"))]: "South Shambles St",
  [String(GetHashKey("STEELE"))]: "Steele Way",
  [String(GetHashKey("STRANGEW"))]: "Strangeways Dr",
  [String(GetHashKey("SUNSTAN"))]: "Sustancia Rd",
  [String(GetHashKey("SVITUS"))]: "San Vitus Blvd",
  [String(GetHashKey("SWISSS"))]: "Swiss St",
  [String(GetHashKey("S_ARSE"))]: "South Arsenal St",
  [String(GetHashKey("S_BOULDP"))]: "South Boulevard Del Perro",
  [String(GetHashKey("S_BROAD"))]: "Strawberry Ave",
  [String(GetHashKey("TACKLE"))]: "Tackle St",
  [String(GetHashKey("TANGER"))]: "Tangerine St",
  [String(GetHashKey("TONGVA"))]: "Tongva Dr",
  [String(GetHashKey("TOWER"))]: "Tower Way",
  [String(GetHashKey("TUGST"))]: "Tug St",
  [String(GetHashKey("UNIONR"))]: "Union Rd",
  [String(GetHashKey("UTOPIAG"))]: "Utopia Gardens",
  [String(GetHashKey("VESPBD"))]: "Vespucci Blvd",
  [String(GetHashKey("VINEPARKD"))]: "Vinewood Park Dr",
  [String(GetHashKey("VINEWB"))]: "Vinewood Blvd",
  [String(GetHashKey("VITUS"))]: "Vitus St",
  [String(GetHashKey("VOOD"))]: "Voodoo Place",
  [String(GetHashKey("WARMWFWY"))]: "Del Perro Fwy",
  [String(GetHashKey("WECLIP"))]: "West Eclipse Blvd",
  [String(GetHashKey("WGAL"))]: "West Galileo Ave",
  [String(GetHashKey("WHISP"))]: "Whispymound Dr",
  [String(GetHashKey("WILDO"))]: "Wild Oats Dr",
  [String(GetHashKey("WINSTON"))]: "Atlee St",
  [String(GetHashKey("WMIRROR"))]: "West Mirror Drive",
  [String(GetHashKey("YORKS"))]: "York St",
  [String(GetHashKey("ZANCUDOA"))]: "Zancudo Ave",
  [String(GetHashKey("ZANCUDOB"))]: "Zancudo Barranca",
  [String(GetHashKey("ZANCUDOG"))]: "Zancudo Grande Valley",
  [String(GetHashKey("ZANCUDOR"))]: "Zancudo Rd",
};

const OTHER_STREET_HASHES = {
  "0x8cd2e019": "Abattoir Ave",
  "0xddcbdc74": "Abe Milton Pkwy",
  "0x4b7b2734": "Ace Jones Dr",
  "0x40d0731c": "Adam's Apple Blvd",
  "0x8ccfea79": "Aguja St",
  "0x7ec39ae2": "Algonquin Blvd",
  "0x92e1c090": "Alhambra Dr",
  "0xb38d48d1": "Alta Pl",
  "0x08b9cc73": "Alta St",
  "0x1ea69437": "Amarillo Vista",
  "0x29e328a9": "Amarillo Way",
  "0x705018b4": "Americano Way",
  "0x97805066": "Applan Way",
  "0xd39fe932": "Armadillo Ave",
  "0x34627a5f": "Atlee St",
  "0x96b2b85f": "Autopia Pkwy",
  "0x62261708": "Backlot Blvd",
  "0x78905544": "Bait St",
  "0x15e466fd": "Banham Canyon Dr",
  "0x26944b16": "Barbareno Rd",
  "0x6f927644": "Bay City Ave",
  "0xedc3b8f4": "Bay City Incline",
  "0xf5efe777": "Baytree Canyon Rd",
  "0xe332ad5d": "Bear St",
  "0x012074ff": "Blvd Del Perro",
  "0x22198c67": "Bridge St",
  "0x5f27252e": "Brouge Ave",
  "0xbcd75b2a": "Buccaneer Way",
  "0x80323559": "Buen Vino Rd",
  "0xb76e170f": "Calafia Rd",
  "0xef6af2c1": "Calafia Way",
  "0x46ec8cf6": "Calais Ave",
  "0x131df79c": "Capital Blvd",
  "0x40468d03": "Carcer Way",
  "0x56f28308": "Carson Ave",
  "0x261c80db": "Cascabel Ave",
  "0xea41fbe8": "Cat-Claw Ave",
  "0x73f16a64": "Cavalry Blvd",
  "0x4900eafd": "Chianski Passage",
  "0xf5196793": "Cholla Rd",
  "0x36a6be4b": "Cholla Springs Ave",
  "0x29ddb334": "Chum St",
  "0x3a82547d": "Chupacabra St",
  "0xe657df40": "Clinton Ave",
  "0x9acc3d68": "Cockingend Dr",
  "0x7e8446dd": "Conquistador St",
  "0x09a04736": "Cortes St",
  "0x186a32d2": "Cougar Ave",
  "0xbea2b02d": "Covenant Ave",
  "0x7bd54361": "Cox Way",
  "0xe10c41be": "Crusade Rd",
  "0xe105d935": "Darien Ave",
  "0x45b1ca3d": "Davis Ave",
  "0x072580d7": "Decker St",
  "0xc8690c80": "Del Perro Fwy",
  "0xf7ea09f7": "Didion Dr",
  "0x6d5eefec": "Dorset Dr",
  "0x6705124c": "Dorset Pl",
  "0x75e5ea92": "Dry Dock St",
  "0x8a00a702": "Duluoz Ave",
  "0xcabef9a8": "Dunstable Dr",
  "0xe0d4a5cb": "Dunstable Ln",
  "0x6635c142": "Dutch London St",
  "0xedeb73e4": "East Galileo Ave",
  "0x6cc8b86e": "East Mirror Dr",
  "0x410a49cd": "Eastbourne Way",
  "0x6418f6fe": "Eclipse Blvd",
  "0xd0b11243": "Edwood Way",
  "0xb44c8e74": "El Burro Blvd",
  "0xcb000216": "El Gordo Dr",
  "0x7fadf1b2": "El Rancho Blvd",
  "0x7bcf327f": "Electric Ave",
  "0x0798837a": "Elgin Ave",
  "0x2e49b265": "Elysian Fields Fwy",
  "0x2c72b469": "Equality Way",
  "0x452f38ac": "Ewing St",
  "0x4d8d8a38": "Exceptionalists Way",
  "0x90963d6a": "Fantastic Pl",
  "0xf3b2be94": "Fenwell Pl",
  "0xf641831c": "Fort Zancudo Approach Rd",
  "0xe94a6ddc": "Forum Dr",
  "0xd0b818e4": "Four Way",
  "0xd9b72921": "Fudge Ln",
  "0x85f5588b": "Galileo Rd",
  "0xd5a607f8": "Gentry Lane",
  "0x534d8027": "Ginger St",
  "0xc431bcee": "Glory Way",
  "0x7f84cc28": "Goma St",
  "0x4dce72d8": "Grapeseed Ave",
  "0x3132b9a5": "Grapeseed Main St",
  "0x4c9260c4": "Greenwich Pkwy",
  "0xcc6e9206": "Greenwich Pl",
  "0xd72068c5": "Greenwich Way",
  "0x00cc5ca0": "Grove St",
  "0x897bb935": "Hanger Way",
  "0xcc9893e2": "Hangman Ave",
  "0x5e315a37": "Hardy Way",
  "0x605d416c": "Hawick Ave",
  "0xdb0c8d26": "Heritage Way",
  "0x764b0e0f": "High Spanish Ave",
  "0x65bcffa3": "Hillcrest Ave",
  "0xa1f822a2": "Hillcrest Ridge Access Rd",
  "0xbc825fe3": "Imagination Ct",
  "0x78b17cf6": "Imperial Blvd",
  "0x4b5b59a7": "Innocence Blvd",
  "0x434cc15c": "Integrity Way",
  "0x8dfdf903": "Invention Ct",
  "0x661aa779": "Jamestown St",
  "0x8f9d12e7": "Joad Ln",
  "0x0a5bff42": "Joshua Rd",
  "0xfb90b746": "Kimble Hill Dr",
  "0xcc628804": "Kortz Dr",
  [String(GetHashKey("LOSPFY"))]: "La Puerta Fwy",
  "0x98295423": "Labor Pl",
  "0x0973b8b6": "Laguna Pl",
  "0x5e4f2ee7": "Lake Vinewood Dr",
  "0xf0089e63": "Las Lagunas Blvd",
  "0x00a55d60": "Lemoyne St",
  "0xde37da0c": "Lesbos Ln",
  "0x2f26bbd7": "Liberty St",
  "0x0bf1ad8d": "Lindsay Circus",
  "0x9db39520": "Little Bighorn Ave",
  "0x5c483e1d": "Lolita Ave",
  "0xec99478c": "Low Power St",
  "0x64306156": "Macdonald St",
  "0xd9c1eace": "Mad Wayne Thunder Dr",
  "0xcf1a660b": "Magellan Ave",
  "0xe7073c86": "Marathon Ave",
  "0x32d92d45": "Marina Dr",
  "0x4a3712c2": "Marlowe Dr",
  "0x7efd9afe": "Melanoma St",
  "0x594944f9": "Meringue Ln",
  "0x639007f6": "Meteor St",
  "0xc99154c3": "Middle Rd",
  [String(GetHashKey("MILTON"))]: "Milton Rd",
  "0x1fa2c931": "Mirror Park Blvd",
  "0x0cc8aae6": "Mirror Pl",
  "0xc122d85f": "Morningwood Blvd",
  "0x906b3d92": "Mountain View Dr",
  "0x9117e6ad": "Movie Star Way",
  "0xd3cd9c6e": "Mt Haan Dr",
  "0x946fdcc9": "Mt Haan Rd",
  "0x5ebc827b": "Mt Vinewood Dr",
  "0x5c033d11": "Mutiny Rd",
  "0xa841625e": "New Empire Way",
  "0x07ab9391": "Nikola Ave",
  "0x7d92ff5a": "Nikola Pl",
  "0x63f44c25": "Niland Ave",
  "0x995c30aa": "Normandy Dr",
  "0xde65dfa8": "North Archer Ave",
  "0x269fdee5": "North Calafia Way",
  "0xa2f6ca31": "North Conker Ave",
  "0xe9d7af42": "North El Rancho Blvd",
  "0x59920dad": "North Rockford Dr",
  "0xb74c0d46": "North Sheldon Ave",
  "0xe34603f3": "North Western Ave",
  "0x245499bf": "Nowhere Rd",
  "0x20101f69": "Occupation Ave",
  "0x192e8516": "Olympic Fwy",
  [String(GetHashKey("ONEIL"))]: "O'Neil Way",
  "0xb87faa60": "Orchardville Ave",
  "0x56563954": "Paleto Blvd",
  "0x520bfb49": "Palomino Ave",
  "0xf5de6511": "Palomino Fwy",
  "0x155fbe2b": "Panorama Dr",
  "0xa5883bde": "Peaceful St",
  "0x909b5591": "Perth St",
  "0x7c7282c1": "Plaice Pl",
  "0x66006a97": "Playa Vista",
  "0xccd0d983": "Popular St",
  "0x7d75c728": "Portola Dr",
  "0xf959d26e": "Power St",
  "0x9a95814f": "Procopio Dr",
  "0x0d5f14e6": "Prosperity St",
  "0xed13b4bc": "Pyrite Ave",
  "0x05eff99a": "Red Desert Ave",
  "0x284cd97b": "Richman St",
  "0x159b0df9": "Rockford Dr",
  "0x62e6db9d": "Rodeo Dr",
  "0xa2854172": "Roy Lowenstein Blvd",
  "0x9735407c": "Rub St",
  "0xb4a79707": "Sam Austin Dr",
  "0xf2c73716": "San Andreas Ave",
  "0xda9dccfb": "San Vitus Blvd",
  "0x0502503f": "Sandcastle Way",
  "0x38e0429c": "Seaview Rd",
  "0x0797dc34": "Selma Ave",
  [String(GetHashKey("SENORA"))]: "Senora Fwy",
  "0x003f6701": "Senora Rd",
  "0x7fcabbad": "Senora Way",
  "0xd529ed93": "Shank St",
  "0x7727141a": "Signal St",
  "0x5c3e7d79": "Sinner St",
  "0x8d6fdc93": "Sinners Passage",
  "0x097d1470": "Sky Way",
  "0x538a9910": "Smoke Tree Rd",
  "0x80cbfbcf": "South Arsenal St",
  "0x73f8ade1": "South Boulevard Del Perro",
  "0xcdf48f9e": "South Mo Milton Dr",
  "0x01d80573": "South Rockford Dr",
  "0x7699aa76": "South Shambles St",
  "0x917fd2ab": "Spanish Ave",
  "0x9da37ee7": "Steele Way",
  "0x3fd7e083": "Strangeways Dr",
  "0x63ab52de": "Strawberry Ave",
  "0x101c10c8": "Supply St",
  "0xa6761da3": "Sustancia Rd",
  "0x4f69f80d": "Swiss St",
  "0x24349a67": "Tackle St",
  "0x3d7a8076": "Tangerine St",
  "0x09503b1f": "Tesla Ave",
  "0x372fd01c": "The Third Way",
  "0x1ebdeabc": "Tongva Dr",
  [String(GetHashKey("TOWER"))]: "Tower Way",
  "0x332a2a65": "Tug St",
  "0x98f59b29": "Union Rd",
  [String(GetHashKey("UTOPIAG"))]: "Utopia Gardens",
  "0x84b5fcb9": "Vespucci Blvd",
  "0xc527457d": "Vinewood Blvd",
  "0xd513f002": "Vinewood Park Dr",
  "0x43ce38ff": "Vitus St",
  "0x983a7d65": "West Eclipse Blvd",
  "0x84d115ad": "West Galileo Ave",
  "0xfffc76b4": "Whispymound Dr",
  "0xb4bb47b3": "Wild Oats Dr",
  "0xce9d4092": "York St",
  "0x21cfaefc": "Zancudo Ave",
  "0x96b41893": "Zancudo Rd",
};

exports(
  "ReverseStreetHash",
  (ReverseStreetHash = (hash) => {
    if (typeof hash !== "string") {
      hash = String(hash);
    }

    const name = STREET_HASHES[hash];

    if (name) {
      return name;
    } else {
      const backup = OTHER_STREET_HASHES[hash];
      if (backup) {
        return backup;
      }

      return "Uknown Street";
    }
  })
);
